### ISSUE TITLE
Sending large size payload

### ISSUE THREAD

**Issue by eliot4321** [eriptic/uoscore-uedhoc#12]
Hi,

When I'm trying to send a big size payload or response I'm getting this error :
Runtime error: coap2oscore(sendPDU->getPDUPointer(), sendPDU->getPDULength(), buf_oscore, &buf_oscore_len, &c_server) error code 1 at src/main.cpp:322

**Comment by StefanHri** [comment]
Client or server? And how big is the payload? In order to activate more precise error informations make sure that you uncomment the line #DEBUG_PRINT += -DDEBUG_PRINT [here ](https://github.com/eriptic/uoscore-uedhoc/blob/e8920192b66db4f909eb9cd3f155d5245c1ae825/makefile_config.mk#L15)

**Comment by eliot4321** [comment]
Client payload, payload size 20 kb, for changes i don't have access to my laptop now, i can do it later. Thanks!

**Comment by eliot4321** [comment]
Even after removing uncommenting nothing happened (I rebuilt the code).

**Comment by StefanHri** [comment]
20KB will not work for sure. Try to split the data in smaller chunks of ca. 100B.

**Comment by eliot4321** [comment]
Thanks for your response @StefanHri, 100B limit is coming from the RFC because I cannot find the information

**Comment by StefanHri** [comment]
No 100B was just a suggestion from me.  The limitation should be the UDP PDU size.

**Comment by StefanHri** [comment]
Should we consider this issue as resolved?
