### ISSUE TITLE
Error compilation in samples/linux-oscore

### ISSUE THREAD

**Issue by rml1977** [eriptic/uoscore-uedhoc#23]
Dear all:

I am installing uoscore-uedhoc in a Ubuntu 22.04.1 just for testing in Linux platform so far.

I have been able to compile everything except the example in linux_oscore

In first place, I had a problem since the make execution did not find file zephyr/net/net_pkt.h .

I did a git clone to download the source files of zephyr, but now I got the error below. 

I just wondering why this sample it is using zephyr. With the other sample linux_edhoc and linux_edhoc_oscore I did not have this issue.

How could you give some help on this?

Thanks in advance.

In file included from /usr/include/zephyr/toolchain.h:50,
                 from /usr/include/zephyr/kernel_includes.h:19,
                 from /usr/include/zephyr/kernel.h:17,
                 from /usr/include/zephyr/net/buf.h:16,
                 from /usr/include/zephyr/net/net_pkt.h:22,
                 from ../../common/sock.h:21,
                 from ../../common/sock.c:11:
/usr/include/zephyr/toolchain/gcc.h:554:2: error: #error processor architecture not supported
  554 | #error processor architecture not supported
      |  ^~~~~
In file included from /usr/include/zephyr/kernel_includes.h:28,
                 from /usr/include/zephyr/kernel.h:17,
                 from /usr/include/zephyr/net/buf.h:16,
                 from /usr/include/zephyr/net/net_pkt.h:22,
                 from ../../common/sock.h:21,
                 from ../../common/sock.c:11:
/usr/include/zephyr/kernel_structs.h:159:26: error: ‘CONFIG_MP_NUM_CPUS’ undeclared here (not in a function)
  159 |         struct _cpu cpus[CONFIG_MP_NUM_CPUS];
      |                          ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/zephyr/kernel_includes.h:31,
                 from /usr/include/zephyr/kernel.h:17,
                 from /usr/include/zephyr/net/buf.h:16,
                 from /usr/include/zephyr/net/net_pkt.h:22,
                 from ../../common/sock.h:21,
                 from ../../common/sock.c:11:
/usr/include/zephyr/syscall.h:11:10: fatal error: syscall_list.h: No such file or directory
   11 | #include <syscall_list.h>
      |          ^~~~~~~~~~~~~~~~

Best Regards.

**Comment by StefanHri** [comment]
Hi rml1977,

thanks for reporting this issue. I provided an update. Let me know if all works as you expects.

In addition I will be interested to learn more about your application. This is because we are working on related projects currently. If you want to share this information in more confidential way you can drop me an eimal stefan.hristozov@eriptic.com.

**Comment by rml1977** [comment]
Hi Stefan:

Yes, it worked (after creating a symbolic link to libuscore-uedhoc.a in /usr/lib )

Thank you so much. 

Best Regards.
