### ISSUE TITLE
Compiling errors with samples

### ISSUE THREAD

**Issue by rml1977** [eriptic/uoscore-uedhoc#51]
Dear all

I got this compiling error or "No such file or directory" messages when compiling different samples. I realized that certainly that , for example, the file sha512.c is not there but _sha512.c , hence the error.

root@h1:/uoscore-uedhoc/samples/linux_edhoc/responder# make
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
mv: cannot stat '../../../externals/tinycrypt/lib/source/sha256.c': No such file or directory
make: 'build/responder' is up to date.

root@h1:/uoscore-uedhoc/samples/linux_oscore/client# make
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
gcc -c -m32 -DDEBUG_PRINT -DLINUX_SOCKETS -I../../../inc/  -I../../common/ -I../../../test_vectors/  -I../../../externals/cantcoap/  -I../../../externals/zcbor/include  -I../../../externals/mbedtls/library  -I../../../externals/mbedtls/include  -I../../../externals/mbedtls/include/mbedtls  -I../../../externals/mbedtls/include/psa  -I../../../externals/compact25519/src/ -I../../../externals/compact25519/src/c25519 -Og -Wall -g -gdwarf-2 -MMD -MP -MF"build/_entropy.d" -DZCBOR_CANONICAL  -Wa,-a,-ad,-alms=build/_entropy.lst src/_entropy.c -o build/_entropy.o
gcc: error: unrecognized command-line option '-m32'
make: *** [Makefile:127: build/_entropy.o] Error 1

root@h1:/uoscore-uedhoc/samples/linux_oscore/server# make
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
gcc -c -m32 -DDEBUG_PRINT -DLINUX_SOCKETS -I../../../inc/  -I../../common/ -I../../../test_vectors/  -I../../../externals/cantcoap/  -I../../../externals/zcbor/include  -I../../../externals/mbedtls/library  -I../../../externals/mbedtls/include  -I../../../externals/mbedtls/include/mbedtls  -I../../../externals/mbedtls/include/psa  -I../../../externals/compact25519/src/ -I../../../externals/compact25519/src/c25519 -Og -Wall -g -gdwarf-2 -MMD -MP -MF"build/_entropy.d" -DZCBOR_CANONICAL  -Wa,-a,-ad,-alms=build/_entropy.lst src/_entropy.c -o build/_entropy.o
gcc: error: unrecognized command-line option '-m32'
make: *** [Makefile:127: build/_entropy.o] Error 1

root@h1:/uoscore-uedhoc/samples/linux_edhoc_oscore/initiator_client# make
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
make: 'build/initiator_client' is up to date.

root@h1:/uoscore-uedhoc/samples/linux_edhoc_oscore/responder_server# make
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
mv: cannot stat '../../../externals/tinycrypt/lib/source/sha256.c': No such file or directory
make: 'build/responder_server' is up to date.

Any suggestion?

Thanks in advance.

**Comment by StefanHri** [comment]
Did you try to do first `make clean` and then `make`?

**Comment by rml1977** [comment]
After writing my message, I realized about that and I already did it. Some issues were fixed. However, trying everything from scratch (including make clean and then make), I still got the following (this is after repeating make to simplify the output)

root@h1:/tmp/uoscore-uedhoc/samples/linux_edhoc/responder# make
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
mv: cannot stat '../../../externals/tinycrypt/lib/source/sha256.c': No such file or directory


/tmp/uoscore-uedhoc/samples/linux_oscore/client# make
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
gcc -c -m32 -DDEBUG_PRINT -DLINUX_SOCKETS -I../../../inc/  -I../../common/ -I../../../test_vectors/  -I../../../externals/cantcoap/  -I../../../externals/zcbor/include  -I../../../externals/mbedtls/library  -I../../../externals/mbedtls/include  -I../../../externals/mbedtls/include/mbedtls  -I../../../externals/mbedtls/include/psa  -I../../../externals/compact25519/src/ -I../../../externals/compact25519/src/c25519 -Og -Wall -g -gdwarf-2 -MMD -MP -MF"build/_entropy.d" -DZCBOR_CANONICAL  -Wa,-a,-ad,-alms=build/_entropy.lst src/_entropy.c -o build/_entropy.o
gcc: error: unrecognized command-line option '-m32'
make: *** [Makefile:127: build/_entropy.o] Error 1

root@h1:/tmp/uoscore-uedhoc/samples/linux_oscore/server# make
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
gcc -c -m32 -DDEBUG_PRINT -DLINUX_SOCKETS -I../../../inc/  -I../../common/ -I../../../test_vectors/  -I../../../externals/cantcoap/  -I../../../externals/zcbor/include  -I../../../externals/mbedtls/library  -I../../../externals/mbedtls/include  -I../../../externals/mbedtls/include/mbedtls  -I../../../externals/mbedtls/include/psa  -I../../../externals/compact25519/src/ -I../../../externals/compact25519/src/c25519 -Og -Wall -g -gdwarf-2 -MMD -MP -MF"build/_entropy.d" -DZCBOR_CANONICAL  -Wa,-a,-ad,-alms=build/_entropy.lst src/_entropy.c -o build/_entropy.o
gcc: error: unrecognized command-line option '-m32'
make: *** [Makefile:127: build/_entropy.o] Error 1

root@h1:/tmp/uoscore-uedhoc/samples/linux_edhoc_oscore/initiator_client# make
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
make: 'build/initiator_client' is up to date.

root@h1:/tmp/uoscore-uedhoc/samples/linux_edhoc_oscore/responder_server# make    
mv: cannot stat '../../../externals/compact25519/src/c25519/sha512.c': No such file or directory
mv: cannot stat '../../../externals/tinycrypt/lib/source/sha256.c': No such file or directory
make: 'build/responder_server' is up to date.

**Comment by StefanHri** [comment]
Hello, Is this resolved? For me running `make clean; make` works.

**Comment by LPFraile** [comment]
Hi everyone.
I also got compiling error on the samples. The only sample that i am able to compile success is  the linux_edhoc/initiator
