### ISSUE TITLE
up-to-date of documentation how to run tests

### ISSUE THREAD

**Issue by AleksanderDemianowski** [eriptic/uoscore-uedhoc#9]
I have some problems to run tests localy. Is the readme file up to date? Maybe description can be splitted into two chapters: embedded devcie and linux host. I tried to run it on dev branch according to [the description](https://github.com/eriptic/uoscore-uedhoc/blob/dev/test/README.MD).

**Comment by StefanHri** [comment]
Hi Aleksander, sorry for the late response. What exactly is not working. I tried aganin on the dev brunch:
```bash
cd test/
source <path>/zephyr-env.sh 
rm -rf build/; west build -b=native_posix
west build -t run
```
and it works for me.
